@tool
extends RefCounted

func write(report: Dictionary, output_path: String) -> bool:
    var file := FileAccess.open(output_path, FileAccess.WRITE)
    if file == null:
        push_error("Could not write Markdown report: %s" % output_path)
        return false

    var summary: Dictionary = report.get("summary", {})
    var lines: Array[String] = []
    lines.append("# Godot Project Doctor Report")
    lines.append("")
    lines.append("Generated: %s" % _sanitize_text(report.get("generated_at", "")))
    lines.append("Project: %s" % _sanitize_text(report.get("project_root", "res://")))
    lines.append("Scan Duration: %d ms" % int(report.get("scan_duration_ms", 0)))
    lines.append("")
    lines.append("## Generated By")
    lines.append("")
    lines.append("- Tool: %s" % _sanitize_text(report.get("tool", "Godot Project Doctor Mini")))
    lines.append("- Version: %s" % _sanitize_text(report.get("tool_version", "unknown")))
    lines.append("")
    lines.append("## Summary")
    lines.append("")
    lines.append("| Severity | Count |")
    lines.append("| --- | ---: |")
    lines.append("| Error | %d |" % summary.get("errors", 0))
    lines.append("| Warning | %d |" % summary.get("warnings", 0))
    lines.append("| Info | %d |" % summary.get("info", 0))
    lines.append("")
    lines.append("## Findings")
    lines.append("")

    var findings: Array = report.get("findings", [])
    if findings.is_empty():
        lines.append("No findings.")
    else:
        for finding: Dictionary in findings:
            lines.append("### %s: %s" % [
                _sanitize_text(str(finding.get("severity", "info")).capitalize()),
                _sanitize_text(finding.get("title", "Finding"))
            ])
            lines.append("")
            lines.append("- Path: `%s`" % _sanitize_code(finding.get("path", "")))
            lines.append("- Check: `%s`" % _sanitize_code(finding.get("id", "unknown")))
            lines.append("- Message: %s" % _sanitize_text(finding.get("message", "")))
            lines.append("- Recommendation: %s" % _sanitize_text(finding.get("recommendation", "")))
            lines.append("")

    file.store_string("\n".join(lines))
    return true

func _sanitize_text(value: Variant) -> String:
    return str(value).replace("\\", "\\\\").replace("\r\n", " ").replace("\n", " ").replace("|", "\\|").strip_edges()

func _sanitize_code(value: Variant) -> String:
    return _sanitize_text(value).replace("`", "\\`")
